run:
  timeout: 5m

linters:
  enable:
    - govet
    - ineffassign
    - misspell
    - gocyclo
    - errcheck
    - staticcheck

linters-settings:
  gocyclo:
    min-complexity: 15

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
