version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - ineffassign
    - misspell
    - gocyclo
    - errcheck
    - staticcheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
